    regions = {
    "afr":"Africa",
    "ase":"Asia, East",
    "ass":"Asia, South",
    "ast":"Asia, Southeast",
    "aus":"Australia",
    "can":"Canada",
    "car":"Caribbean",
    "ese":"Eastern Europe",
    "eng":"England",
    "fra":"France",
    "ger":"Germany",
    "gre":"Greece",
    "ini":"Ireland & Northern Ireland",
    "isr":"Israel",
    "ita":"Italy",
    "lam":"Latin America",
    "mex":"Mexico",
    "mie":"Middle East",
    "pai":"Pacific Islands",
    "pol":"Poland",
    "rus":"Russia",
    "sca":"Scandinavia",
    "sco":"Scotland",
    "spa":"Spain",
    "usa":"U.S., Mid-Atlantic",
    "usm":"U.S., Midwestern",
    "use":"U.S., New England",
    "usn":"U.S., Northwestern",
    "uss":"U.S., Southern",
    "ust":"U.S., Southwestern",
    "usw":"U.S., Western",
    "wal":"Wales",
    }

    affiliations = {
    "aug":"Augustan",
    "bea":"Beat",
    "bam":"Black Arts Movement",
    "blm":"Black Mountain",
    "con":"Confessional",
    "fug":"Fugitive",
    "geo":"Georgian",
    "har":"Harlem Renaissance",
    "ima":"Imagist",
    "lan":"Language Poetry",
    "mid":"Middle English",
    "mod":"Modern",
    "nys":"New York School",
    "nyt":"New York School (2nd Generation)",
    "obj":"Objectivist",
    "ren":"Renaissance",
    "rom":"Romantic",
    "vic":"Victorian"
    }

    subjects = {
    "lov":"Love",
    "nat":"Nature",
    "soc":"Social Commentaries",
    "rel":"Religion",
    "liv":"Living",
    "res":"Relationships",
    "act":"Activities",
    "art":"Arts & Sciences",
    "myt":"Mythology & Folklore"
    }